baseURL: "https://lazyprompt.vercel.app/"
languageCode: "en-us"
title: "Lazy Prompt ðŸš€"
# theme: "PaperMod"
paginate: 12

enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: true

outputs:
  home:
    - HTML
    - JSON

# Simplified Params
params:
  profileMode:
    subtitle: "The Largest AI Prompt Library"
    imageUrl: "/images/logo_dark.png"

  # Social Icons
  socialIcons:
    - name: "github"
      url: "https://github.com/"
