baseURL: "https://lazyprompt.vercel.app/"
languageCode: "ko-kr"
title: "Lazy Prompt ğŸš€"
# theme: "PaperMod"

params:
  env: production
  defaultTheme: "auto"
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  
  # Main Sections
  mainSections: 
    - "posts"

  # Profile Mode
  profileMode:
    enabled: true
    title: "Lazy Prompt ğŸš€"
    subtitle: "ê²Œìœ¼ë¥¸ ìë“¤ì„ ìœ„í•œ AI í”„ë¡¬í”„íŠ¸ ë„ì„œê´€"
    imageUrl: "https://cdn-icons-png.flaticon.com/512/4712/4712109.png"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: "Github"
        url: "https://github.com"

  # Social Icons
  socialIcons:
    - name: "github"
      url: "https://github.com/"
